/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  savageSidebar: [{type: 'autogenerated', dirName: 'savage'}],
  extremeSidebar: [{type: 'autogenerated', dirName: 'extreme'}],
  criterionSidebar: [{type: 'autogenerated', dirName: 'criterion'}],
};

export default sidebars;
